### ISSUE TITLE
Can't generate correct ninja rules for certain Makefile

### ISSUE THREAD

**Issue by nigangkaka** [google/kati#215] opened 2020-11-12 07:40 UTC
The following Makefile can't generate correct ninja rules.
(PS: I have an main.cc contains simple "hello world" demo")

```
LOCAL_PATH            := .

TARGET                = Hello


EXTRA_LDFLAGS    = -Wl,--gc-sections -Wl,--strip-all


LOCAL_SRC	+= $(wildcard ${LOCAL_PATH}/*.cc)

OUT_BIN = $(patsubst ${LOCAL_PATH}/%.cc, ${LOCAL_PATH}/%.bin, ${LOCAL_SRC})


${LOCAL_PATH}/%.o: ${LOCAL_PATH}/%.cc
	@g++ -c $^ -o $@

$(LOCAL_PATH)/%.bin : $(LOCAL_PATH)/%.o
	@objcopy -O binary $^ $@
	@g++ $^ $(EXTRA_LDFLAGS) -o ${TARGET}
	@rm -rf $^
	
create_bin: $(OUT_BIN)
	@echo "Create Bin files Done"

.PHONY: all

all: create_bin


```

It only generates: 

```
# Generated by kati d9189545ad0cc0d6d49e7d10d4ffcf622739e86b

pool local_pool
 depth = 16

build _kati_always_build_: phony

# Makefile:27
rule rule0
 description = build $out
 command = /bin/sh -c "echo \"Create Bin files Done\""
build create_bin: rule0 main.bin

default create_bin
```

Then if I run "make" under the folder which contains the Makefile I will get "main.bin" and Hello. 

But if I run "source ./ && ./ninjia.sh" i get the follow error message:

> ninja: error: 'main.bin', needed by 'create_bin', missing and no known rule to make it

**Comment by Colecf** [comment] 2022-11-18 08:08
Duplicate of https://github.com/google/kati/issues/245

**Closed by Colecf** 2022-11-18 08:08 UTC
